## 测试KNN的性能

In [9]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets 

In [10]:
iris = datasets.load_iris()

In [11]:
X = iris.data
y = iris.target

In [12]:
X.shape

(150, 4)

In [13]:
y.shape

(150,)

## train_test_split

In [15]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [16]:
len(X)

150

In [17]:
shuffle_index = np.random.permutation(len(X))

In [18]:
shuffle_index

array([ 47,  16,  88, 121, 107,  71, 113,  54, 100,  15,  50,  13,  65,
       124, 109, 139,  41,  75,  48, 149,   8,  18,  40,  96, 148,  37,
        78, 135,  86, 125, 127, 119,  42,  63,  81, 105,  10, 110, 103,
       115, 114, 126, 136, 108,  21, 118,  97,  92,  12,  35,  46,  68,
       104,  77,  85, 140,  93,  62, 101, 143,  91,  32,  80,   3, 130,
        38,  19,  79,  25,  82,  66,  52,   6,  72, 147,  58,  20, 146,
        83, 112,  36, 131,  56,  39, 122,  43,  64,  44,  31, 128,  17,
       106,   7,   0,  98,  90,   9,  87,  26, 141,  34, 134,  89,  14,
        60, 137,  28,  69,  53,  49,  29,  33,  95,  67, 144, 142,  73,
       138,  57, 111, 117, 129,  45,  23,  70,  99,   5, 145,  30,  22,
        27,  24,  76,  94,  59, 102, 120,  84, 132,   1,   2, 116, 123,
       133,  61,  55,  74,   4,  51,  11])

In [19]:
test_ratio = 0.2
test_size = int(len(X) * test_ratio)

In [20]:
test_size

30

In [21]:
test_index = shuffle_index[:test_size]
train_index = shuffle_index[test_size:]

In [22]:
x_train = X[train_index]
y_train = y[train_index]

x_test = X[test_index]
y_test = y[test_index]

In [25]:
x_train
x_train.shape

(120, 4)

In [27]:
y_train
y_train.shape

(120,)

In [28]:
from sklearn.neighbors import KNeighborsClassifier

d:\Users\wzy\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [29]:
KNN_classifier = KNeighborsClassifier(n_neighbors=6)

In [30]:
KNN_classifier.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=6, p=2,
           weights='uniform')

In [32]:
y_predict = KNN_classifier.predict(x_test)

In [33]:
y_predict

array([0, 0, 1, 2, 2, 1, 2, 1, 2, 0, 1, 0, 1, 2, 2, 2, 0, 1, 0, 2, 0, 0,
       0, 1, 2, 0, 1, 2, 1, 2])

In [34]:
y_test

array([0, 0, 1, 2, 2, 1, 2, 1, 2, 0, 1, 0, 1, 2, 2, 2, 0, 1, 0, 2, 0, 0,
       0, 1, 2, 0, 1, 2, 1, 2])

In [36]:
sum(y_predict == y_test)

30

In [37]:
sum(y_predict == y_test) / len(y_test)

1.0

In [38]:
from sklearn.model_selection import train_test_split

In [40]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [41]:
x_train.shape

(120, 4)

In [42]:
y_train.shape

(120,)