## Numpy.array 基本操作

In [1]:
import numpy as np

In [2]:
z = np.arange(10)
z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
X = np.arange(15).reshape(3, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### 基本属性

In [4]:
z.ndim

1

In [5]:
X.ndim

2

In [6]:
z.shape

(10,)

In [7]:
X.shape

(3, 5)

In [8]:
z.size

10

In [9]:
X.size

15

### numpy.array 数据访问

In [10]:
z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
z[0]

0

In [12]:
z[-1]

9

In [13]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [14]:
X[0][0]

0

In [15]:
X[(0, 0)]

0

In [16]:
X[(0, 2)]

2

In [17]:
X[0, 2]

2

In [18]:
X[2, 2]

12

In [19]:
z[0:5]

array([0, 1, 2, 3, 4])

In [20]:
z[:5]

array([0, 1, 2, 3, 4])

In [21]:
z[5:]

array([5, 6, 7, 8, 9])

In [22]:
z[5:-1]

array([5, 6, 7, 8])

In [23]:
z[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [24]:
z[::2]

array([0, 2, 4, 6, 8])

In [25]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [26]:
X[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

In [27]:
X[:2, ::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [28]:
X[::-1, ::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [29]:
X[0]

array([0, 1, 2, 3, 4])

In [30]:
X[0,:]

array([0, 1, 2, 3, 4])

In [31]:
X[:,0]

array([ 0,  5, 10])

In [32]:
X[:,0].ndim

1

In [33]:
subX = X[:2, :3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [34]:
subX2 = X[:2, :3].copy()
subX2

array([[0, 1, 2],
       [5, 6, 7]])

In [35]:
subX2[0, 0] = 100
subX2

array([[100,   1,   2],
       [  5,   6,   7]])

In [36]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### Reshape

In [37]:
z.shape

(10,)

In [38]:
z.ndim

1

In [39]:
z.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [40]:
z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
A = z.reshape(2, 5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [42]:
z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
B = z.reshape(1,10)
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [44]:
B.ndim

2

In [45]:
B.shape

(1, 10)

In [46]:
z.shape

(10,)

In [47]:
z.reshape(10, -1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [48]:
z.reshape(-1, 10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

### 合并操作

In [49]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [50]:
x

array([1, 2, 3])

In [51]:
y

array([3, 2, 1])

In [52]:
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [53]:
z = np.array([666, 666, 666])

In [54]:
np.concatenate([x, y, z])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [69]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

In [70]:
np.concatenate([A, A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [71]:
np.concatenate([A, A], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [73]:
A2 = np.concatenate([A, z.reshape(1, -1)])
A2

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [74]:
np.vstack([A, z])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [76]:
B = np.full((2, 2), 100)
B

array([[100, 100],
       [100, 100]])

In [79]:
np.hstack([A, B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

In [80]:
np.hstack([A, z])

ValueError: all the input arrays must have same number of dimensions

### 分割操作

In [82]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
x1, x2, x3 = np.split(x, [3, 7])
x1

array([0, 1, 2])

In [87]:
x2

array([3, 4, 5, 6])

In [88]:
x3

array([7, 8, 9])

In [89]:
x1, x2 = np.split(x, [5])

In [90]:
x1

array([0, 1, 2, 3, 4])

In [91]:
x2

array([5, 6, 7, 8, 9])

In [93]:
A = np.arange(16).reshape([4,-1])
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [94]:
A1, A2 = np.split(A, [2])

In [95]:
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [96]:
A2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [97]:
A1, A2 = np.split(A, [2], axis=1)

In [98]:
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [99]:
A2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [101]:
up, lo = np.vsplit(A, [2])

In [102]:
up

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [103]:
lo

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [104]:
l, r = np.hsplit(A, [2])

In [105]:
l

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [106]:
r

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [107]:
r[0, 1] = 100
r

array([[  2, 100],
       [  6,   7],
       [ 10,  11],
       [ 14,  15]])

In [108]:
A

array([[  0,   1,   2, 100],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15]])

In [109]:
data = np.arange(16).reshape([4,-1])
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [110]:
x, y = np.hsplit(data, [-1]).copy()

In [111]:
x

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [112]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [114]:
y[:, 0]

array([ 3,  7, 11, 15])

In [115]:
y[:, -1]

array([ 3,  7, 11, 15])