## numpy.array 中的运算
给定一个向量， 让向量中每一个数乘以1
a = (0, 1, 2)
a*2 = (0, 2, 4)

In [1]:
import numpy as np

In [2]:
n = 10
L = [i for i in range(n)]

In [3]:
2 * L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
A = []
for i in L:
    A.append(2*i)

In [5]:
A

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [6]:
n = 1000000
L = [i for i in range(n)]

In [7]:
n

1000000

In [8]:
%%time
A = []
for i in L:
    A.append(i*2)

Wall time: 369 ms


In [9]:
%%time
A = [i*2 for i in L]

Wall time: 168 ms


In [10]:
L = np.arange(n)

In [27]:
%%time
A = np.array(e*2 for e in L)

Wall time: 0 ns


In [28]:
A

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [29]:
%%time
A = 2 * L

Wall time: 5 ms


In [30]:
L

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [32]:
A = 2 * L
A

array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

### Universal Function

In [35]:
X = np.arange(1, 16).reshape((3, 5))
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [36]:
X+1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [37]:
X-1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [38]:
X*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [39]:
X/2

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5]])

In [40]:
X//2

array([[0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5],
       [5, 6, 6, 7, 7]], dtype=int32)

In [41]:
X**2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225]], dtype=int32)

In [42]:
X%2

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]], dtype=int32)

In [43]:
1 / X

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667]])

In [44]:
np.abs(X)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [45]:
np.sin(X)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [46]:
np.exp(X)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06]])

In [48]:
np.power(3, X)

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]], dtype=int32)

In [49]:
np.log(X)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [50]:
np.log2(X)

array([[0.        , 1.        , 1.5849625 , 2.        , 2.32192809],
       [2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809],
       [3.45943162, 3.5849625 , 3.70043972, 3.80735492, 3.9068906 ]])

In [51]:
np.log10(X)

array([[0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ],
       [0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ],
       [1.04139269, 1.07918125, 1.11394335, 1.14612804, 1.17609126]])

### 矩阵运算

In [52]:
A = np.arange(4).reshape(2,-1)
A

array([[0, 1],
       [2, 3]])

In [54]:
B = np.full((2,2), 10)
B

array([[10, 10],
       [10, 10]])

In [55]:
A + B

array([[10, 11],
       [12, 13]])

In [57]:
A - B

array([[-10,  -9],
       [ -8,  -7]])

In [58]:
A / B

array([[0. , 0.1],
       [0.2, 0.3]])

In [59]:
A // B

array([[0, 0],
       [0, 0]], dtype=int32)

In [60]:
A.dot(B)

array([[10, 10],
       [50, 50]])

In [61]:
A.T

array([[0, 2],
       [1, 3]])

In [62]:
A

array([[0, 1],
       [2, 3]])

In [64]:
C = np.full((3,3), 888)
C

array([[888, 888, 888],
       [888, 888, 888],
       [888, 888, 888]])

In [65]:
A + C

ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

In [68]:
A.dot(X)

ValueError: shapes (2,2) and (3,5) not aligned: 2 (dim 1) != 3 (dim 0)

### 向量和矩阵的运算

In [70]:
v = np.array([1, 2])
v

array([1, 2])

In [71]:
A

array([[0, 1],
       [2, 3]])

In [77]:
v + A

array([[1, 3],
       [3, 5]])

In [79]:
A.shape

(2, 2)

In [80]:
A.shape[0]

2

In [84]:
np.vstack([v] * A.shape[0])

array([[1, 2],
       [1, 2]])

In [85]:
v

array([1, 2])

In [82]:
np.tile(v, (2, 1))

array([[1, 2],
       [1, 2]])

In [86]:
np.tile(v, (2, 2))

array([[1, 2, 1, 2],
       [1, 2, 1, 2]])

In [87]:
v

array([1, 2])

In [88]:
A

array([[0, 1],
       [2, 3]])

In [89]:
v.dot(A)

array([4, 7])

In [90]:
A.dot(v)

array([2, 8])

### 矩阵的逆

In [92]:
invA = np.linalg.inv(A)

In [93]:
invA

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [94]:
A.dot(invA)

array([[1., 0.],
       [0., 1.]])

In [95]:
invA.dot(A)

array([[1., 0.],
       [0., 1.]])

In [96]:
X = np.arange(16).reshape((2,-1))
X

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [97]:
np.linalg.inv(X)

LinAlgError: Last 2 dimensions of the array must be square

In [102]:
pinvX = np.linalg.pinv(X)

In [103]:
pinvX

array([[-1.35416667e-01,  5.20833333e-02],
       [-1.01190476e-01,  4.16666667e-02],
       [-6.69642857e-02,  3.12500000e-02],
       [-3.27380952e-02,  2.08333333e-02],
       [ 1.48809524e-03,  1.04166667e-02],
       [ 3.57142857e-02, -3.46944695e-18],
       [ 6.99404762e-02, -1.04166667e-02],
       [ 1.04166667e-01, -2.08333333e-02]])

In [104]:
X.dot(pinvX)

array([[ 1.00000000e+00, -6.24500451e-17],
       [ 1.55431223e-15,  1.00000000e+00]])