## numpy.array

In [2]:
import numpy as np

In [3]:
np.__version__

'1.16.2'

### python List 特点

In [4]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
L[5]

5

In [7]:
L[5] = 100
L

[0, 1, 2, 3, 4, 100, 6, 7, 8, 9]

In [9]:
L[5] = "Nechine Learning"
L

[0, 1, 2, 3, 4, 'Nechine Learning', 6, 7, 8, 9]

In [10]:
import array

In [11]:
arr = array.array('i', [i for i in range(10)])
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr[5]

5

In [14]:
arr[5] = 100
arr[5]

100

### numpy array

In [28]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
type(nparr)

numpy.ndarray

In [30]:
nparr[5]

5

In [32]:
nparr[5] = 100
nparr[5]

100

In [33]:
nparr.dtype

dtype('int32')

In [34]:
nparr[5] = 5.3
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
nparr.dtype

dtype('int32')

In [36]:
nparr2 = np.array([1, 2, 3.0])

In [37]:
nparr2.dtype

dtype('float64')

In [38]:
nparr2

array([1., 2., 3.])

### 创建numpy.array的方法

In [39]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [40]:
np.zeros(10).dtype

dtype('float64')

In [41]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [43]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [44]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [45]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [48]:
np.full((3, 5), fill_value=666.)

array([[666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.]])

### arange

In [49]:
[i for i in range(0, 20, 2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [50]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [51]:
[i for i in range(0, 20, 0.2)]

TypeError: 'float' object cannot be interpreted as an integer

In [52]:
np.arange(0, 20, 0.2)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4, 10.6, 10.8,
       11. , 11.2, 11.4, 11.6, 11.8, 12. , 12.2, 12.4, 12.6, 12.8, 13. ,
       13.2, 13.4, 13.6, 13.8, 14. , 14.2, 14.4, 14.6, 14.8, 15. , 15.2,
       15.4, 15.6, 15.8, 16. , 16.2, 16.4, 16.6, 16.8, 17. , 17.2, 17.4,
       17.6, 17.8, 18. , 18.2, 18.4, 18.6, 18.8, 19. , 19.2, 19.4, 19.6,
       19.8])

### linspace

In [53]:
np.linspace(0, 20, 10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [54]:
np.linspace(0, 20, 11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

### random

In [55]:
np.random.randint(0, 10, 10)

array([6, 4, 9, 9, 8, 0, 3, 4, 6, 3])

In [56]:
np.random.randint(0, 10, (5, 3))

array([[2, 0, 8],
       [4, 8, 9],
       [1, 7, 8],
       [9, 8, 8],
       [8, 7, 6]])

In [57]:
np.random.randint(0, 1, 10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [59]:
np.random.randint(4, 8, size=10)

array([7, 5, 5, 5, 4, 4, 4, 7, 5, 6])

In [60]:
np.random.randint(4, 8, size=(3, 5))

array([[6, 7, 7, 4, 6],
       [7, 4, 6, 7, 4],
       [7, 4, 7, 4, 5]])

In [61]:
np.random.seed(666)

In [62]:
np.random.randint(4, 8, size=(3, 5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [63]:
np.random.randint(4, 8, size=(3, 5))

array([[4, 6, 5, 7, 4],
       [6, 4, 7, 5, 6],
       [4, 7, 5, 5, 5]])

In [64]:
np.random.seed(666)
np.random.randint(4, 8, size=(3, 5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [65]:
np.random.random()

0.2811684913927954

In [66]:
np.random.random(10)

array([0.46284169, 0.23340091, 0.76706421, 0.81995656, 0.39747625,
       0.31644109, 0.15551206, 0.73460987, 0.73159555, 0.8578588 ])

In [67]:
np.random.random((3, 5))

array([[0.76741234, 0.95323137, 0.29097383, 0.84778197, 0.3497619 ],
       [0.92389692, 0.29489453, 0.52438061, 0.94253896, 0.07473949],
       [0.27646251, 0.4675855 , 0.31581532, 0.39016259, 0.26832981]])

In [69]:
np.random.normal() # 符合正态分布

1.1806359754812632

In [78]:
np.random.normal(10, 100)  # 均值10,方差:100

16.102403954600113

In [79]:
np.random.normal(10, 100, (3, 5))

array([[ 117.85613781,  -69.78357213,  127.01325983,   21.21217026,
          13.18538839],
       [  -9.20628514,   88.6112843 , -159.04631421,  -88.87390714,
          41.39856302],
       [  49.63856739,   67.65658375,    2.98059308,  101.25043617,
         110.4704966 ]])

In [82]:
np.random.normal(size=10)

array([-1.52902454,  0.92487532,  0.18305429,  0.34543496, -0.8131543 ,
        1.06325382,  0.25866385,  0.47285107,  1.0319698 , -0.16045655])