In [4]:
import numpy as np
L = np.random.random(100)

In [5]:
L

array([0.97501996, 0.32776595, 0.20233728, 0.79476037, 0.33993085,
       0.41988889, 0.21916631, 0.33782532, 0.88897085, 0.31011992,
       0.47913559, 0.46538807, 0.21956469, 0.26595983, 0.43018938,
       0.69606924, 0.37419802, 0.62546739, 0.82271907, 0.90898126,
       0.95532333, 0.45723721, 0.11823058, 0.93113541, 0.27347417,
       0.14398521, 0.86026428, 0.10395784, 0.78797039, 0.61129817,
       0.25217295, 0.93701165, 0.21997457, 0.8229742 , 0.18952438,
       0.98120716, 0.95006019, 0.21951493, 0.79483629, 0.86742348,
       0.07709876, 0.80563681, 0.41382286, 0.80641379, 0.08179591,
       0.85062679, 0.27388726, 0.70660576, 0.55414842, 0.65804206,
       0.93925666, 0.69970431, 0.85601363, 0.37470416, 0.95607859,
       0.5907308 , 0.67814343, 0.88605978, 0.51037171, 0.80267997,
       0.22465481, 0.4800048 , 0.08407443, 0.20162271, 0.49219365,
       0.73603092, 0.4222239 , 0.41924318, 0.37816928, 0.27316164,
       0.29422327, 0.51209943, 0.33115506, 0.90096082, 0.67583

In [6]:
sum(L)

51.79593539697355

In [7]:
np.sum(L)

51.79593539697353

In [9]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

152 ms ± 2.87 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.36 ms ± 52.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [10]:
np.min(big_array)

1.293142048996998e-07

In [11]:
np.max(big_array)

0.999999362424933

In [12]:
big_array.min()

1.293142048996998e-07

In [13]:
big_array.max()

0.999999362424933

In [14]:
big_array.sum()

500191.652536224

In [15]:
X = np.arange(16).reshape((4,-1))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [16]:
np.sum(X)

120

In [18]:
np.sum(X, axis=0)

array([24, 28, 32, 36])

In [19]:
np.sum(X, axis=1)

array([ 6, 22, 38, 54])

In [23]:
np.prod(X+1)

2004189184

In [24]:
np.mean(X)

7.5

In [25]:
np.median(X)

7.5

In [26]:
np.percentile(big_array, q=50)

0.5002272020429659

In [27]:
np.median(big_array)

0.5002272020429659

In [28]:
for p in [0, 25, 50, 75, 100]:
    print(np.percentile(big_array, q=p))

1.293142048996998e-07
0.2499874014668881
0.5002272020429659
0.750596313403001
0.999999362424933


In [29]:
np.var(big_array)

0.08342197389602314

In [30]:
np.std(big_array)

0.2888286237477566

In [31]:
x = np.random.normal(0, 1, size=1000000)

In [32]:
np.mean(x)

0.0014079441666135027

In [33]:
np.std(x)

1.0010026333394029

### 索引

In [34]:
np.min(x)

-4.597845641376617

In [35]:
np.argmin(x)

206405

In [36]:
x[206405]

-4.597845641376617

In [37]:
np.argmax(x)

408006

In [38]:
x[408006]

4.769377663533484

In [39]:
np.max(x)

4.769377663533484

### 排序和使用索引

In [40]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [41]:
np.random.shuffle(x)

In [42]:
x

array([12, 11,  3,  9,  8,  1,  0, 13,  4, 10,  6,  7, 15,  2, 14,  5])

In [43]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [44]:
x

array([12, 11,  3,  9,  8,  1,  0, 13,  4, 10,  6,  7, 15,  2, 14,  5])

In [45]:
x.sort()

In [46]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [47]:
X = np.random.randint(10, size=(4,4))
X

array([[1, 0, 7, 9],
       [8, 7, 8, 1],
       [0, 1, 4, 1],
       [1, 6, 3, 5]])

In [48]:
np.sort(X)

array([[0, 1, 7, 9],
       [1, 7, 8, 8],
       [0, 1, 1, 4],
       [1, 3, 5, 6]])

In [49]:
np.sort(X,axis=1)

array([[0, 1, 7, 9],
       [1, 7, 8, 8],
       [0, 1, 1, 4],
       [1, 3, 5, 6]])

In [50]:
np.sort(X,axis=0)

array([[0, 0, 3, 1],
       [1, 1, 4, 1],
       [1, 6, 7, 5],
       [8, 7, 8, 9]])

In [51]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [52]:
np.random.shuffle(x)

In [53]:
x

array([ 4, 14,  9, 12,  0,  5,  8,  2,  3, 13, 11,  7,  6, 10,  1, 15])

In [54]:
np.argsort(x)

array([ 4, 14,  7,  8,  0,  5, 12, 11,  6,  2, 13, 10,  3,  9,  1, 15],
      dtype=int64)

In [55]:
x

array([ 4, 14,  9, 12,  0,  5,  8,  2,  3, 13, 11,  7,  6, 10,  1, 15])

In [56]:
np.partition(x, 3)

array([ 1,  0,  2,  3,  4,  5,  8, 14, 12, 13, 11,  7,  6, 10,  9, 15])

In [57]:
x

array([ 4, 14,  9, 12,  0,  5,  8,  2,  3, 13, 11,  7,  6, 10,  1, 15])

### Fancy Indexing

In [58]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [59]:
x[3]

3

In [60]:
x[3:9]

array([3, 4, 5, 6, 7, 8])

In [61]:
inx = [3, 5, 8]

In [62]:
x[inx]

array([3, 5, 8])

In [63]:
inx = np.array([[0, 2],
               [1, 3]])
x[inx]

array([[0, 2],
       [1, 3]])

In [64]:
X = x.reshape(4,-1).copy()
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [65]:
row = np.array([0, 1, 2])
col = np.array([1, 2, 3])

In [66]:
X[row, col]

array([ 1,  6, 11])

In [67]:
X[0,col]

array([1, 2, 3])

In [68]:
X[:2, col]

array([[1, 2, 3],
       [5, 6, 7]])

In [69]:
col = [True, False, True, False]

In [70]:
X[1:3, col]

array([[ 4,  6],
       [ 8, 10]])

### numpy.array 的比较

In [71]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [72]:
x < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [73]:
x[x<3]

array([0, 1, 2])

In [74]:
x[x>3]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [75]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [76]:
X < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [77]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [78]:
np.sum(x <= 3)

4

In [79]:
np.any(x == 0)

True

In [80]:
np.any(x < 0)

False

In [81]:
np.all(x >= 0)

True

In [82]:
np.all(x > 0)

False

In [83]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [84]:
np.sum((x > 3) & (x < 10))

6

In [85]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [89]:
X[X[:,-1] % 3 == 0, :]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

In [ ]:
`